# semantickitti_04 config

# Map information
resolution: 0.3
num_class: 20 # Number of classes

# Sampling resolutions
free_resolution: 100 # Free space sampling resolution
ds_resolution: 0.1 # Downsampling factor

# Information about range-finder data
scan_num: 1100 # How many scans to use
max_range: -1 # Sensor max range (m)

# Dataset information
input_data_prefix: predicted/velodyne/
input_label_prefix: predicted/predictions/
lidar_pose_file: poses.txt
gt_label_prefix: predicted/labels/
evaluation_result_prefix: evaluations/
# input_data_prefix: semantickitti_04/velodyne/
# input_label_prefix: semantickitti_04/predictions/
# lidar_pose_file: semantickitti_04/poses.txt
# gt_label_prefix: semantickitti_04/labels/
# evaluation_result_prefix: evaluations/
query: true
visualize: true
